"""create tasks table

Revision ID: 8c9330c5be3c
Revises: 
Create Date: 2026-06-26 17:41:42.312672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c9330c5be3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('context_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_agent_id', 'tasks', ['agent_id'], unique=False)
    op.create_index('ix_tasks_context_id', 'tasks', ['context_id'], unique=False)
    op.create_index('ix_tasks_state', 'tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_state', table_name='tasks')
    op.drop_index('ix_tasks_context_id', table_name='tasks')
    op.drop_index('ix_tasks_agent_id', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
